# Generated by Django 5.1.2 on 2024-10-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_servicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='imagen1',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='imagen3',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='imagen4',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='valoracion',
        ),
        migrations.AddField(
            model_name='servicio',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='redes_sociales',
            field=models.CharField(max_length=255),
        ),
    ]
