# Generated by Django 3.2.19 on 2024-11-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20241101_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('turista', 'Turista'), ('admin', 'Administrador'), ('oferente', 'Oferente')], default='turista', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tipo_oferente',
            field=models.CharField(choices=[('artesano', 'artesano'), ('bienesServicios', 'bienesServicios'), ('cabanas', 'cabanas')], default='artesano', max_length=20),
        ),
    ]
