# Generated by Django 5.1.2 on 2024-10-16 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_user_servicio_usuario_remove_servicio_imagen1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_servicios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha_accion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
