# Generated by Django 3.2.19 on 2024-11-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20241101_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('turista', 'Turista'), ('admin', 'Administrador'), ('oferente', 'Oferente')], default='oferente', max_length=20),
        ),
    ]
