# Generated by Django 5.1.2 on 2024-10-17 00:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_servicio_administrador_servicio_fecha_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudoferente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
