# Generated by Django 3.2.19 on 2024-11-08 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_is_first_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudoferente',
            name='user',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.DeleteModel(
            name='SolicitudOferente',
        ),
    ]
