# Generated by Django 3.2.19 on 2024-11-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LugarTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(decimal_places=15, max_digits=20)),
                ('longitud', models.DecimalField(decimal_places=15, max_digits=20)),
            ],
        ),
    ]
