# Generated by Django 3.2.19 on 2024-11-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='tipo_oferente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
