# Generated by Django 3.2.19 on 2024-11-11 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicio_tipo_oferente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='correo',
        ),
    ]
