# Generated by Django 3.2.19 on 2024-11-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_servicio_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_servicios/'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_servicios/'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_servicios/'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes_servicios/'),
        ),
    ]
